development:
  adapter: mysql2
  encoding: utf8
  database: survey_app_development
  pool: 5
  username: root
  password: deadface
  collation: utf8_general_ci
  host: 127.0.0.1
  port: 3306

test:
  adapter: mysql2
  encoding: utf8
  database: survey_app_test
  pool: 5
  username: root
  password:
  collation: utf8_general_ci
  host: 127.0.0.1
  port: 3306

staging:
  adapter: mysql2
  encoding: utf8
  database: survey_app_staging
  pool: 5
  username: root
  password: 
  collation: utf8_general_ci
  host:
  port:

production:
  adapter: mysql2
  encoding: utf8
  database: survey_app_production
  pool: 5
  username: root
  password: 
  collation: utf8_general_ci
  host:
  port: